apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-jobs
  namespace: cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-workspaces
  namespace: cicd
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: maven-repo
  namespace: cicd
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}